### ISSUE TITLE
Double notification sound on SMS arrival..

### ISSUE THREAD

**Issue by Cactus-World** [felixb/smsdroid#21]
Hi, 
on Lollipop whenever a message arrives the notification is done twice-is SMSDroid perhaps listening to SMS_DELIVERED AND SMS_RECEIVED broadcasts?
Best, 
Cactus World

**Comment by felixb** [comment]
You need to disable the notifications in the default sms app.

**Comment by Cactus-World** [comment]
Sorry to say that, but this was already the fact and does not solve the issue. Btw, under Lollipop you can only have one default messaging application and this is set to SMSDroid.

**Comment by Cactus-World** [comment]
I just looked at the code and noticed that my suspicion in the first place seems to be the right one...

**Comment by Cactus-World** [comment]
Hi Felix, 
I just created a patch that should solve this issue. Maybe you want to give it a try - at least for me it seems to work ;-).
Best, 
Carsten


[SingleNotificationSound.zip](https://github.com/felixb/smsdroid/files/63985/SingleNotificationSound.zip)

**Comment by felixb** [comment]
please send the patch as pull request. it's much easier to review.
I just got a newborn. So I'm quite out of spare time right now. ;)

**Comment by Cactus-World** [comment]
Hi, 
congrats! ;-) Hope she/he is allright. Well, yes, I'll try to figure out how to do that (just recently switched to GIT from CVS/Subversion and I am still learning...) Nevertheless it's just two things patched in SmsReceiver.java and MmsReceiver.java - not more than 10 lines over all...
CU, 
Carsten

**Comment by felixb** [comment]
Any news on submitting a PR?

**Comment by Cactus-World** [comment]
Hallo Felix, 
sorry, hier ist Land unter seit geraumer Zeit. Ich habe den Patch noch verbessert und setze dann erst den PR-jetzt bin ich aber erstmal 3 Wochen weg.
Viele Grüße, 
Carsten

Am 12. Januar 2016 13:31:59 MEZ, schrieb Felix Bechstein <notifications@github.com>:
>Any news on submitting a PR? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/felixb/smsdroid/issues/21#issuecomment-170897633

----------------------------------------------------
              Cactus World
   
 	    Multimedia & IT 
    Komponenten & -dienstleistungen

   	    Kakteenprodukte

    Im Litzelholz 94, D-54293 Trier

                Inhaber:
      Dipl.-Inform. Carsten Tichy
----------------------------------------------------

**Comment by felixb** [comment]
please check out this build/branch

http://ub0r.de/files/43038ff88f1ba31ecbed31701cdddeabff291af4-SMSdroid-release.apk

**Comment by Cactus-World** [comment]
Oh, darn, finally just figured out how to and sent the pull request with my changes and did not notice you already created another branch...

**Comment by felixb** [comment]
please verify the new version of the fix in #29.
i'll close this issue. please comment on #29 directly.

**Comment by rphair** [comment]
I have commented on issue #29 with my experience that this is still an open bug, at least on Nexus 5 with CM13.  I hope at least a currently valid APK file link can be posted here, so concerned users can test the code if necessary before the fix referred to in #29 is made available to the public ASAP.

**Comment by rphair** [comment]
apologies; that was pull request #29 rather than "issue" & the recently posted APK there fixes the problem.
