### ISSUE TITLE
Option to chose weather to send via WebSMS or natively 

### ISSUE THREAD

**Issue by voyager** [felixb/smsdroid#24]
Hi Felix, 

Another thing I'd like to ask is if it possible to choose weather SMSdroid will send message or it will be sent via WebSMS. 

I like using WebSMS as a relay only when I'm roaming, but in other cases is prefer that SMSdroid sends them the regular way. 

Thanks.

**Comment by felixb** [comment]
This is already possible by not setting a default app for sending. You can unset the default app in Android's settings for the choosen app.

**Comment by voyager** [comment]
I'm not sure we're on the same page here. 

SMSdroid and WebSMS merged somehow, so I cannot stop SMSdroid from trying to send every message via WebSMS :) 

But I think I've bypassed the issue here by actually still pressing WebSMS-reply button in SMSdroid, but then when WebSMS opens changing the connector to SMS.

**Comment by felixb** [comment]
We are. You need to go to Android's apps settings. Choose WebSMS. Clear "default app".

**Comment by voyager** [comment]
I was there, WebSMS did not have any defaults set, SMSdroid did, but cleaning those did not change anything :) 

One more thing, if I reply from an existing conversation in SMSdroid, I'm asked about the connector, but when I go to compose a new message from the SMSdroid, WebSMS opens a what used to be a default connector, no dialogue to choose from several connectors.
