### ISSUE TITLE
Additional Information in SMSdroid (suggestion)

### ISSUE THREAD

**Issue by stefangreim** [felixb/smsdroid#25]
Hey,
it would be great if one could see how much characters are left (or already in use) during writing a message E. g.:
for one SMS: 105/160
for more: 167/320

Additional (but I know, that could be more complicated) it would be great to see how much free sms (see the info "Guthaben: 3/10" for GMX connector) are left.

Hopefully some good ideas. But its not a showstopper at all.

greetz!
Stefan

**Comment by felixb** [comment]
1. before reaching the limit of one sms, a counter is shown already
2. the websms app does this already, smsdroid does not know anything about your gmx account or that the message is to be sent with this particular connector.
