### ISSUE TITLE
Can't receive new SMS

### ISSUE THREAD

**Issue by Doc73** [felixb/smsdroid#26]
Dear Developer,
I installed a cooked rom on my Asus TF300TG (http://forum.xda-developers.com/showthread.php?t=2425390).
Unfortunately, the dev of the ROM missed to add an app for sending and receiving SMS.

With SMSDroid I can read the SMSs, but don't receive  at all new SMSs.

App as ZERO Comunicazione (https://play.google.com/store/apps/details?id=com.jb.zerosms&hl=it) works very well, but I prefer open-source apps like yours.

Let me know if you need some other info.

Thank you very much in advance,
Domenico

**Comment by felixb** [comment]
Smsdroid relays on the vendor sms app to write new messages into the database. With Android 4.4 new messages should be written by smsdroid on arrival, if set as default app. 
Anyway, I can't support tables which are not designed for receiving message. It's just to rare and I don't have a device to test it.
