### ISSUE TITLE
SMS from twilio

### ISSUE THREAD

**Issue by chris-rudmin** [felixb/smsdroid#27]
@felixb I'm creating an app to receive and send SMS via twilio (https://www.twilio.com/sms). When I receive the message in my app, Is there an intent I can publish so that the message is received by SMS droid?

**Comment by chris-rudmin** [comment]
@felixb I checked through your code and I didn't see a way to do it via an intent.  Do you see any problems if I write directly to the inbox and then post my own notification which would then open SMSDroid?

**Comment by chris-rudmin** [comment]
Update: Found out writing to the inbox is a no-go because I need to become the default messaging app to do so. Any other ideas?

**Comment by felixb** [comment]
I guess, you need to build your own sms app, if you want to receive messages from some remote service. It's basically a messenger app. 
If you want sending apps only, you might choose to implement a WebSMS connector.
