### ISSUE TITLE
Any chance on having a recent version pushed to F-Droid?

### ISSUE THREAD

**Issue by tgp1994** [felixb/smsdroid#30]
I'd love to start using this app, and an app store/repo would be the most convenient way for me to get it. Unfortunately, it looks like the latest version on F-Droid is two and a half years old. Can a more recent version, 1.6.9 for example, be sent to the F-Droid repository?

**Comment by felixb** [comment]
Well, I never published the app on any third party app store. I won't do it in future because of my limited spare time. 
You could ask the guy publishing the app in F-droid or update it yourself. 
You can build the app from source as well.

**Comment by IzzySoft** [comment]
@felixb if you'd consider to simply attach the `apk` file to the resp. `releases/` (see [creating releases](https://help.github.com/articles/creating-releases/) in the Github help, it's easy and won't take more than a minute), I'd offer to pick it up and place it into [my repo](https://android.izzysoft.de/repo), which can be used with the F-Droid client.

**Comment by felixb** [comment]
I believe  f-droid does not allow usage of non-free libraries, right?

**Comment by IzzySoft** [comment]
@felixb I don't have to apply that rule to my repo, do I? :smile_cat:

**Comment by felixb** [comment]
this is the current release rolling out on google play just now:

http://ub0r.de/files/8bba57fa90c743f9dfc43bc9a6f9e630d1471aeb-SMSdroid-release-1.7.1.apk

**Comment by IzzySoft** [comment]
And as it's now attached in `releases/` as well: [here](https://apt.izzysoft.de/fdroid/index/apk/de.ub0r.android.smsdroid) it can be found in my repo :smiley_cat:
