### ISSUE TITLE
resource leak: database cursor not closed

### ISSUE THREAD

**Issue by andrew659** [felixb/smsdroid#31]
Dear developers,

The database cursor used in the fetchMmsParts() method of Message class is not closed.

https://github.com/felixb/smsdroid/blob/master/SMSdroid/src/main/java/de/ub0r/android/smsdroid/Message.java

```
Cursor cursor = cr.query(URI_PARTS, null, PROJECTION_PARTS[INDEX_MID] + " = ?",
                new String[]{String.valueOf(id)}, null);
        if (cursor == null || !cursor.moveToFirst()) {
            return;
        }
```

If the cursor is empty but not null (moveToFirst() returns false), the method will return early and the cursor will be left open. Is it a bug? Thanks.

**Comment by felixb** [comment]
Looks like it's a bug. Feel free to send a PR.

**Comment by andrew659** [comment]
@felixb 

Glad to help. I will send a PR later.

**Comment by chewi** [comment]
I guess you can close this now. :smile:
