### ISSUE TITLE
"Mark button" or "select button" not working well

### ISSUE THREAD

**Issue by blackmaryline** [felixb/smsdroid#33]
#### Expected behavior

"Mark all" or "select" messages button on SMSdroid app is expected to be used to mark messages for either marking them as read or unread or probably to select messages to delete from the SMS folder

#### Actual behavior
The "Mark button" or "select button" found on SMSdroid app doesn't mark messages, rather the response it will give is "mark all as read" and there's nothing been marked 

#### How to reproduce
Download SMSdroid App from Google play store on your android device, the mark or select button is found at the right top corner of the app, short press or long press the button to use the function, the response is not different from what is said above and no action is taken

* Browser: SmsDroid App
* Operating system: Android 7.0 nougat
* Phone: Camon CX air

#### Recording Of The Bug

https://youtu.be/qz4fn14dkSQ

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@timmyeu/mark-button-or-select-button-not-working-well">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by felixb** [comment]
I can't reproduce the bug anymore. I fixed mark messages as read from notification with the upcoming release.
