### ISSUE TITLE
add notification channels for android 8+

### ISSUE THREAD

**Issue by felixb** [felixb/smsdroid#35]
current implementation will not show any notification on android 8+

**Comment by chewi** [comment]
That's quite a major bug! Admittedly I've only just noticed the problem but I think it was working before the last update?

**Comment by felixb** [comment]
do you mind testing this fix?

https://ub0r.de/files/44b226d5b4cb2eb5aa8e0fd4968985624a07da07-SMSdroid-logRelease.apk

**Comment by chewi** [comment]
That does indeed work, thank you! However, the Mark Read button doesn't seem to do anything?

**Comment by felixb** [comment]
Thanks for your feedback. I fixed the read button as well.
